-- ═══════════════════════════════════════════════════════════════════════════
-- OBSOLETO - NO EJECUTAR
-- ═══════════════════════════════════════════════════════════════════════════
-- Este script daba SELECT/UPDATE/DELETE sobre pedidos al rol "anon", cuya
-- key es pública en el frontend: cualquier visitante podía leer los datos
-- personales de todos los clientes y modificar o borrar pedidos.
--
-- Usa en su lugar: SUPABASE_FIX_RLS_SECURITY.sql
-- (acceso de admin mediante Supabase Auth + tabla admin_users)
-- ═══════════════════════════════════════════════════════════════════════════
